services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Cpsit\EventSubmission\:
    resource: '../Classes/*'

  _instanceof:
    Cpsit\EventSubmission\Factory\ApiResponse\ApiResponseFactoryInterface:
      tags: [ 'EventSubmission.ApiResponseFactory' ]

  Cpsit\EventSubmission\Factory\ApiResponse\ApiResponseFactory:
    public: true
    arguments:
      $factories: !tagged_iterator {tag: 'EventSubmission.ApiResponseFactory', index_by: 'ApiResponseFactory' }
