name: Tests
on: [ push, pull_request ]

jobs:
  tests:
    name: PHP ${{ matrix.php-version }} & TYPO3 ${{ matrix.typo3-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - typo3-version: 11.5
            php-version: 8.2
            coverage: 1
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Prepare environment
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer:${{matrix.composer-version}}
          coverage: xdebug

      # Define Composer cache
      - name: Get Composer cache directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Define Composer cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: tests-php-${{ matrix.php-version }}-typo3-${{ matrix.typo3-version }}
          restore-keys: |
            tests-php-${{ matrix.php-version }}-typo3-

      # Install dependencies
      - name: Install TYPO3 and Composer dependencies
        run: composer require typo3/cms-core:"^${{ matrix.typo3-version }}" --no-progress

      # Run tests
      - name: Run tests
        run: |
          composer test:unit -- \
          --coverage-clover .Build/log/coverage/clover.xml \
          --log-junit .Build/log/junit.xml

  coverage:
    name: Test coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Prepare environment
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: composer:v2
          coverage: pcov

      # Install dependencies
      - name: Install Composer dependencies
        uses: ramsey/composer-install@v2
        with:
          dependency-versions: highest

      # Run Unit tests
      - name: Build coverage directory
        run: mkdir -p .Build/log/coverage
      - name: Run Unit tests with coverage
        run: composer test:unit:coverage

      # Report coverage
      - name: Fix coverage path
        working-directory: .Build/log/coverage
        run: sed -i 's#/home/runner/work/event-submission/event-submission#${{ github.workspace }}#g' clover.xml
      - name: CodeClimate report
        uses: paambaati/codeclimate-action@v5.0.0
        if: env.CC_TEST_REPORTER_ID
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageLocations: |
            ${{ github.workspace }}/.Build/log/coverage/clover.xml:clover
      - name: codecov report
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: .Build/log/coverage
          fail_ci_if_error: true
          verbose: true
